### ISSUE TITLE
Suggestion: For resolver map destructuring, `:or` is interpreted as optional

### ISSUE THREAD

**Issue by eneroth** [wilkerlucio/pathom3#158]
We wrap resolvers with the following function internally:

```clojure 
(defn destructure-map->resolver-input-keys
  "Takes a destructuring map and parses it into a map of two vectors,
  `:req` and `:opt`.

  Keys that are destructured into a var that appears in `:or` are
  interpreted as optional (`:opt`). Otherwise, they are interpreted
  as required (`:req`)."
  [m]
  (let [optional?       (-> m :or keys set)
        sym->target-key #(if (optional? %) :opt :req)]
    (reduce-kv (fn [res k v]
                 (cond
                   (symbol? k)
                   (update res (sym->target-key k) conj v)

                   (and (keyword? k) (= "keys" (name k)))
                   (reduce (fn [res sym]
                             (update res (sym->target-key sym)
                               conj (keyword (or (namespace sym)
                                               (namespace k)) (name sym))))
                     res
                     v)

                   :else
                   (throw (ex-info (str "Don't know how to destructure `" k "`") m))))
      {:req []
       :opt []}
      (dissoc m :as :or))))
```

It's mostly based on the equivalent function in Pathom proper, but allows for `:or` to signal that an argument is optional. We take the resultant vectors and populate `::pco/input`with them, wrapping in `pco/?` where optional.

It turns out that it's a quite intuitive and convenient way to signal optionality of arguments, even if it sometimes ends up in `:or {my-thing nil}` when there's no good default value, but we just want to mark it optional.

Maybe this inference would have a place in Pathom itself?

**Comment by wilkerlucio** [comment]
I like the idea, and I also feel a bit annoyed when I have to add `::pco/input` just because some argument is optional. I'll give it some consideration, thanks for the suggestion!

**Comment by wilkerlucio** [comment]
Very cool. Sounds pretty interesting to me. Also, I can't think of a scenario where the user destructures a value and doesn't want it on the input. It must be on the input anyway for it to work. Thanks for sharing the idea.

I made some analysis on it, and that's what I got:

## Problem

To make one of the inputs optional, a user must repeat all the other inputs, even if they have no special properties. For example:

```clojure
(pco/defresolver display-name
  [{:user/keys [name nickname name-prefix]}]
  {::pco/input [:user/name (pco/? :user/nickname) :user/display-name]}
  {:user/display-name (str name-prefix (or nickname name))})
```

A similar problem occurs when one of the inputs requires a nested definition:

```clojure
(pco/defresolver user-score-display
  [{:user/keys [display-name scores]}]
  {::pco/input [:user/display-name {:user/scores [:score/points]}]}
  {:user/scores-display
   (str display-name
        " latest scores: "
        (str/join ", " (map :score/points scores)))})
```

## Solution Space

### Merge inferred input with explicit input instead of replacing it

We can modify the `defresolver` implementation to merge the inferred input with the
explicit input instead of replacing it. With that change the user is able to get the
same result as the previous example usign the following form:

```clojure
(pco/defresolver display-name
  [{:user/keys [name nickname name-prefix]}]
  {::pco/input [(pco/? :user/nickname)]}
  {:user/display-name (str name-prefix (or nickname name))})
```

This solution addresses both the issues with user repetition on optionals and nested
fields. It's a general solution to override pieces of the inferred query without
repeating the ordinary ones.

**Mutation params**

The same change should also be applied to `defmutation` `::pco/params` inferrence to
keep both macros behavior consistent.

**Trade-off**

In a scenario where a user does override the input partially but doesn't use the part
that's only inferred. In this scenario the user will have an extra impact on loading something he is not
using, for example:

```clojure
(pco/defresolver inferred-not-used [{:keys [foo bar]}]
  {::pco/input [:foo]}
  {:other (str "foo " foo)})
```

This turns into the user the responsibility to make sure the resolver isn't destructuring
unsued bindings.

### Support optional description via :or section of destructuring

Currently, the `defresolver` macro doesn't use the `:or` action of the destructuring
for any effect. This opens the possibility of making it an integrated part of the
descrution expression for Pathom operation inference.

It would solve the repetition encountered in our example using the following form:

```clojure
(pco/defresolver display-name
  [{:user/keys [name nickname name-prefix]
    :or        {nickname nil}}]
  {:user/display-name (str name-prefix (or nickname name))})
```

**Default value evaluation**

In this scenario, we must choose how to evaluate the optional default value. We can
evaluate it at macro reading time, making it a constant. Or we can wrap that
in a function and call it in case it needs to use the default.

[Decision Matrix on default value evaluation](https://docs.google.com/spreadsheets/d/1u4GZPKQQzn1ZucjFof7JlmP4v8cHR5V9aXIlkCXKq5k/edit#gid=278049114)

**Trade-off**

We must consider this change will reify a semantic meaning for `:or` in the context of Pathom macros, once
it's defined, we can't pick a different semantic without doing a breaking change.

---

The solutions are not mutually exclusive, and both may be adopted.

**Comment by eneroth** [comment]
> A similar problem occurs when one of the inputs requires a nested definition.

It's definitely the case that not everything boils down to a simple K/V lookup, which is why we chose the input vector to take precedence over that which is inferred from destructuring. You sort of _can_ do nested destructuring in Clojure:

```clojure
(let [{{hello :world} :dog} {:dog {:world "cat"}}]
  hello)
;; => "cat"
```

But now we've definitely left the realm of ergonomics (and what's idiomatic), which was the main point of the above. If I saw this going on in our codebase, I'd ask for it to be rewritten to a simple destructure + explicit query in the input vector.

If you extrapolate the above to a more complex query, the destructuring would be a monster. It's possible to parse into a query, but I'm pretty convinced that it's not something to encourage. In our case (as you can see in the `:else` branch of the `cond` above), we've explicitly forbidden this.

> In this scenario the user will have an extra impact on loading something he is not using

This is true, but equally true if the input vector was used instead. With a decent linter, unused destructured arguments can be caught. Agreed; perhaps recommend the usage of a linter in the docs, and after that it's the responsibility of the user to optimize the requirements of the resolver.

> Currently, the `defresolver` macro doesn't use the `:or` action of the destructuring for any effect

I think it's a bit more than that. If I recall correctly, the Pathom specs currently scream when they encounter `:or`.

> We can evaluate it at macro reading time, making it a constant.

I would definitely recommend compile-time interpretation of this. Dynamically altering the destructure map is a path to insanity. Clojure semantics and idiomatics have destructuring down as something that declares what is known to be needed at write/compile/build time, not something that dynamically changes at run time. It's better to align with this than to work around it, in my opinion.

What kind of voodoo would you have to be up to for there to be a requirement for the _destructuring map_ to change at runtime? Surely at that point you'd just bind a symbol and do dynamic extractions on it?

> We must consider this change will reify a semantic meaning for `:or`

Absolutely, and it's worth considering. I'd argue that it reifies the semantic meaning for what it actually is. 

The semantic meaning of `:or` is to indicate optionality. If you were to write a spec for a function argument that destructures a map, and has `:or`, you'd allow for the key to be present or absent. If you did not, your `:or` would be pointless, as Clojure's `:or` runs on `contains?` semantics, and not on `nil?` semantics. If you pass `nil` to a parameter that is in `:or`, the `:or` won't run.

```clojure
(let [{a   :a
       :or {a "dog"}} {:a nil}]
  a)
;; => nil
```

So `:or` really talks about "is the key _present_ or _absent_", not "is the key `nil` or not". This seems to me to be the exact semantics of `pco/?`. So it seems that Clojure semantics around this seems to line up pretty well with Pathom.

**Comment by wilkerlucio** [comment]
> What kind of voodoo would you have to be up to for there to be a requirement for the destructuring map to change at runtime? Surely at that point you'd just bind a symbol and do dynamic extractions on it?

Since I have full control, what I would do is just wrap the value in a `fn`, store it, and run it when the default is necessary. But still also think the compile time evaluation is better, having coherence with Clojure is the most important IMO.
