### ISSUE TITLE
unexpected errors reported with attribute-errors-plugin and new error handling

### ISSUE THREAD

**Issue by jmayaalv** [wilkerlucio/pathom3#59]
When running with the `attribute-errors-plugin` invalid errors are present in the output when all attrs are resolved.

``` clojure
(def db {:a {1 {:a/id 1 :a/code "a-1"}
               2 {:a/id 2 :a/code "a-2"}}
           :f {1 {:f/id 1 :f/code "f-1"}
               2 {:f/id 2 :f/code "f-2"}}
           :b {1 [{:f/id 1}]}
           :c {1 [{:f/id 2}]}})

(pco/defresolver a [input]
    {::pco/input  [:a/id]
     ::pco/output [:a/id :a/code]
     ::pco/batch? true}
    (mapv #(get-in db [:a (:a/id %)]) input))

(pco/defresolver f [input]
  {::pco/input  [:f/id]
     ::pco/output [:f/id :f/code]}
    (get-in db [:f (:f/id input)]))

(pco/defresolver b [input]
    {::pco/input  [:a/id]
     ::pco/output [{:a/b [:f/id]}]
     ::pco/batch? true}
    (mapv (fn [{:a/keys [id]}]
           {:a/b (get-in db [:b id])}) input))

(pco/defresolver c [input]
    {::pco/input  [:a/id]
     ::pco/output [{:a/c [:f/id]}]
     ::pco/batch? true}
    (mapv (fn [{:a/keys [id]}]
           {:a/c (get-in db [:c id])}) input))

(-> (p.plugin/register (pbip/attribute-errors-plugin))
      (pci/register [a f b c])
      (p.eql/process [{[:a/id 1] [:a/code {:a/b [:f/id :f/code]} {:a/c [:f/id :f/code]}]}]))

=> 
{[:a/id 1]
 {:a/b [#:f{:id 1, :code "f-1"}],
  :a/c [#:f{:id 2, :code "f-2"}],
  :com.wsscode.pathom3.connect.runner/attribute-errors
  #:a{:code
      #:com.wsscode.pathom3.error{:error-type
                                  :com.wsscode.pathom3.error/attribute-unreachable},
      :b
      #:com.wsscode.pathom3.error{:error-type
                                  :com.wsscode.pathom3.error/node-errors,
                                  :node-error-details {}},
      :c
      #:com.wsscode.pathom3.error{:error-type
                                  :com.wsscode.pathom3.error/node-errors,
                                  :node-error-details {}}}}}

```

**Comment by wilkerlucio** [comment]
I did an initial inspection, I see the problem only occurs when the resolver is batch. Looking further.

**Comment by wilkerlucio** [comment]
There is a bigger problem under this one. The issue here is that the error handler is based on the plugin extension `::wrap-run-graph!`, and I notice a problem with it now. The issue is that in the case of batches, the exit point of the extension is after the first pass on that entity, normally its true, but in case of batch it isn't. In the batch case, the process will pause, and at that pause moment the plugin will finish. But since the data is waiting for batch, the error plugin doesn't see the data there, and things its missing.

Not sure how to about yet. But maybe the current plugin form wouldn't be enough, because in this case the "exit" of the run-graph is detached from the start of it. A simpler option is having a different extension point that knows about this finish vs batch finish situation.

Gotta think more about this.

**Comment by wilkerlucio** [comment]
More details on the approach: https://roamresearch.com/#/app/wsscode/page/Zf7QBEK6m
