### ISSUE TITLE
Optional outputs cause missing input errors

### ISSUE THREAD

**Issue by soulplant** [wilkerlucio/pathom3#90]
Thanks so much for Pathom, it's a beautiful idea!

I'm noticing that while it's legal to make an optional request for a field that isn't provided by a resolver, if I make an optional request for a field whose provider depends on an unprovided field it errors. For example:

```
(ns example
  (:require
   [com.wsscode.pathom3.connect.operation :as pco]
   [com.wsscode.pathom3.connect.indexes :as pci]
   [com.wsscode.pathom3.interface.eql :as p.eql]
   [com.wsscode.pathom3.error :as p.error]))

(pco/defresolver a->b
  [{:keys [a]}]
  {::pco/output [:b]}
  {})

(pco/defresolver b->c
  [{:keys [b]}]
  {::pco/output [:c]}
  {:c "c"})

(let [env (pci/register
           [a->b
            b->c])]

  (p.eql/process env {:a 1} [(pco/? :b)])  ; => {}
  (p.eql/process env {:a 1} [(pco/? :c)])) ; throws

   Insufficient data calling resolver 'example/b->c. Missing attrs :b
   {:required {:b {}}, :available {}, :missing {:b {}}}
```

In the above scenario I would expect both calls to process to return `{}` without error, but the latter request fails. Is this expected behaviour?

**Comment by wilkerlucio** [comment]
Hello, thanks for the report, I agree the behavior, in this case, should be to ignore that missing dependency.

The reason it happens is that the strict mode considers any exception a critical failure that should flow up. And currently, the missing input to call resolver throws the insufficient data exception. I think I should change this, maybe add some data to the exception that holds it instead of flowing up, or find another way to handle insufficient data (without exceptions).

**Comment by wilkerlucio** [comment]
Closing the issue for now, please re-open if you believe there is still something to track here.
